[target.'cfg(all())']
# Enable global lints
rustflags = [
  # Allows
  "-Aclippy::let_unit_value",
  "-Aclippy::extra_unused_lifetimes", # <- Problems with diesel::Insertable macro expansion.
  "-Aclippy::use_self",               # <- Problems with macro expansions.
  "-Aclippy::result_large_err",

  # Denies
  "-Drustdoc::broken_intra_doc_links",
  "-Dclippy::mod_module_files",

  # Warns
  "-Wmissing_docs",
  "-Wrust_2018_idioms",
  "-Wunsafe_code",
  "-Wunused_imports",
  "-Wvariant_size_differences",
  "-Wlet_underscore_drop",
  "-Wclippy::checked_conversions",
  "-Wclippy::cloned_instead_of_copied",
  # "-Wclippy::cognitive_complexity",  # <- Too much shit to fix, enable by service first
  "-Wclippy::dbg_macro",
  "-Wclippy::decimal_literal_representation",
  "-Wclippy::empty_enum",
  "-Wclippy::enum_glob_use",
  "-Wclippy::equatable_if_let",
  "-Wclippy::explicit_deref_methods",
  "-Wclippy::explicit_into_iter_loop",
  "-Wclippy::explicit_iter_loop",
  "-Wclippy::filter_map_next",
  "-Wclippy::filter_map_next",
  "-Wclippy::fn_params_excessive_bools",
  "-Wclippy::if_not_else",
  "-Wclippy::implicit_clone",
  "-Wclippy::implicit_saturating_sub",
  "-Wclippy::imprecise_flops",
  "-Wclippy::index_refutable_slice",
  "-Wclippy::items_after_statements",
  "-Wclippy::large_types_passed_by_value",
  "-Wclippy::manual_filter_map",
  "-Wclippy::manual_find_map",
  "-Wclippy::manual_ok_or",
  "-Wclippy::manual_unwrap_or",
  "-Wclippy::map_flatten",
  "-Wclippy::map_unwrap_or",
  "-Wclippy::match_same_arms",
  #"-Wclippy::missing_const_for_fn", <- too many false positives.
  "-Wclippy::missing_errors_doc",
  "-Wclippy::mut_mut",
  "-Wclippy::needless_continue",
  "-Wclippy::needless_pass_by_value",
  "-Wclippy::ref_option_ref",
  "-Wclippy::single_match_else",
  "-Wclippy::manual_let_else",
  "-Wclippy::suspicious_operation_groupings",
  "-Wclippy::type_repetition_in_bounds",
  "-Wclippy::unnecessary_sort_by",
  "-Wclippy::unnecessary_wraps",
  "-Wclippy::useless_format",
]

[registries.crates-io]
protocol = "sparse"

[unstable]
sparse-registry = true
